x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    env_file: ./backend/.env
    depends_on:
      - postgres
      - redis
    logging: *default-logging

  frontend:
    build:
      context: ./frontend
    logging: *default-logging

  engine:
    build:
      context: ./engine
    env_file: ./engine/.env
    depends_on:
      - redis
    logging: *default-logging

  worker:
    build:
      context: ./worker
    env_file: ./worker/.env
    depends_on:
      - postgres
      - redis
    logging: *default-logging

  postgres:
    image: timescale/timescaledb:2.28.1-pg17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=exchange
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging: *default-logging

  redis:
    image: redis:7.2
    logging: *default-logging

volumes:
  postgres_data:
  redis_data:
