services:
  backend:
    build:
      context: ./backend
      target: runner
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: runner
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped

  engine:
    build:
      context: ./engine
      target: runner
    env_file:
      - ./engine/.env
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: ./worker
      target: runner
    env_file:
      - ./worker/.env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=exchange
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

volumes:
  postgres_data:
